### PR TITLE
Support encrypted passwords for local security realm

### LINKED ISSUE #713: Support bcrypt hashed passwords on disk for users
In its current state, in order to create a default user on startup, one must specify the user and the password in plain text inside of a YAML file.

I would like to instead support creation of users which have pre-hashed passwords on disk so a malicious user can't read the passwords from a file on disk.

### PR DESCRIPTION
**Pull request by mglazer**
This commit bumps the Jenkins supported version to 2.164
which is the first version that includes the necessary API
hooks for using bcrypted passwords.

Fixes #713:

This is the upstream Jenkins PR where this was made part of the core product: jenkinsci/jenkins#3817

- [X] Please describe what you did

- [X] Link to issue you're working on if there's a relevant one

- [X] Did you provide a test-case to demonstrate feature actually works / issue is fixed ?

- [X] Please also consider adding a line to [CHANGELOG.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by mglazer** [comment]
@timja sorry about the new PR for this.

**Comment by mglazer** [comment]
I'm going to have to look into why the BackwardsCompatibilityTest is failing.

**Comment by casz** [comment]
Well based on master, there is a huge difference between 2.60.1 and 2.164.1. Let me handle the work bumping the Jenkins core version then you can work on your the actual PR

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 1]
```diff
@@ -33,13 +41,32 @@ public HudsonPrivateSecurityRealmConfigurator() {
...
+                    } else {
+                        target.createAccount(user.id, user.password);
+                    }
                 }
             }
         ));
         return describe;
     }
 
+    static boolean jenkinsSupportsHashedPasswords() {
```
Comment (timja) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: shouldn't be needed anymore with core version bump

File: plugin/src/test/java/io/jenkins/plugins/casc/core/JdkConfiguratorTest.java [hunk 2]
```diff
@@ -30,9 +29,5 @@ public void should_configure_maven_tools_and_global_config() {
 
         InstallSourceProperty installSourceProperty = jdk.getProperties().get(InstallSourceProperty.class);
         Assert.assertEquals(1, installSourceProperty.installers.size());
-
-        JDKInstaller installer = installSourceProperty.installers.get(JDKInstaller.class);
```
Comment (timja) [inline plugin/src/test/java/io/jenkins/plugins/casc/core/JdkConfiguratorTest.java]: revert this change and merge in master

Comment (mglazer) [reply plugin/src/test/java/io/jenkins/plugins/casc/core/JdkConfiguratorTest.java]: Done

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 1 above)
Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: OK, wasn't sure how much backwards compatibility support was desired for this project.

**Comment by casz** [comment]
I'd suggest we rebase your work on the 2.164.1 branch: https://github.com/jenkinsci/configuration-as-code-plugin/tree/JenkinsV164.1

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 3]
```diff
@@ -33,13 +41,32 @@ public HudsonPrivateSecurityRealmConfigurator() {
                     .collect(Collectors.toList()))
             .setter((target, value) -> {
                 for (UserWithPassword user : value) {
-                    target.createAccount(user.id, user.password);
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: I'd suggest moving the for each loop to a method, allowing you to use method reference instead of lambda :smile:

Creating better readability and reducing indentation.

Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Made a bunch of fixes to this class, including ensuring proper typing was used. Thanks for the feedback.

**Comment by mglazer** [comment]
Rebased on top of V164.1

**Comment by casz** [comment]
Suggestion, rebase onto `JenkinsV164.1` once more after I got a green build on Jenkins CI.   
If we get a green build here, I can merge it into `JenkinsV164.1` than we can discuss merge of #790 into master.

Your also welcome to wait for `JenkinsV164.1` merge into master :smile:

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 4]
```diff
@@ -17,27 +21,45 @@
...
-                    .collect(Collectors.toList()))
-            .setter((target, value) -> {
-                for (UserWithPassword user : value) {
+            .getter(HudsonPrivateSecurityRealmConfigurator::getter)
+            .setter(HudsonPrivateSecurityRealmConfigurator::setter)
+        );
+        return describe;
+    }
+
+    private static Collection<UserWithPassword> getter(HudsonPrivateSecurityRealm target) {
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: A `Collection` is not the best choice for generic collections, and I'd suggest `List` as that is what you are returning in the `toList()` at the return statement.
Reason being `Collection` is too abstract

```suggestion
    private static List<UserWithPassword> getter(HudsonPrivateSecurityRealm target) {
```

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 5]
```diff
@@ -17,27 +21,45 @@
...
+        return target.getAllUsers().stream()
+                .map(u -> new UserWithPassword(u.getId(), null)) // password isn't actually stored, only hashed
+                .collect(Collectors.toList());
+    }
+
+    private static void setter(HudsonPrivateSecurityRealm target, Collection<UserWithPassword> value) throws IOException {
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Ditto on the `Collection` here

```suggestion
    private static void setter(HudsonPrivateSecurityRealm target, List<UserWithPassword> value) throws IOException {
```

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 6]
```diff
@@ -17,27 +21,45 @@
  */
 @Extension
 @Restricted(NoExternalUse.class)
-public class HudsonPrivateSecurityRealmConfigurator extends DataBoundConfigurator {
+public class HudsonPrivateSecurityRealmConfigurator extends DataBoundConfigurator<HudsonPrivateSecurityRealm> {
+    private static final Logger logger = LoggerFactory.getLogger(HudsonPrivateSecurityRealmConfigurator.class);
+    /// matches HudsonPrivateSecurityRealm.JBCRYPT_HEADER, requires Jenkins >= 164.1
+    private static final String HASHED_PASSWORD_PREFIX = "#jbcrypt:";
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: https://github.com/jenkinsci/jenkins/blob/bf333b4637da11a9aa6e0e5e5bef5361bda2e35a/core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java#L875 should have been public but alas :cry:

File: CHANGELOG.md [hunk 7]
```diff
@@ -2,6 +2,8 @@
 
 ## 1.9 (not released yet)
 
+- Add support for bcrypt encrypted passwords. Use with a `#jbcrypt:` prefix.
```
Comment (casz) [inline CHANGELOG.md]: Hint you can most likely remove this if #794 gets approved. Going forward we will use PR titles for release note hints.

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 8]
```diff
@@ -8,7 +8,11 @@
 import org.kohsuke.accmod.Restricted;
 import org.kohsuke.accmod.restrictions.NoExternalUse;
 import org.kohsuke.stapler.DataBoundConstructor;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Please don't use `org.slf4j.Logger`  
So far we have been using `java.util.logging.Logger`

If you want us to switch to slf4j that requires a separate PR :sweat_smile:

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 4 above)
Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: The interface for `MultivaluedAttribute` is `Attribute<Owner, Collection<Type>>`. I could extend something different, but I didn't want to rewrite the code that much for this feature.

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 6 above)
Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Indeed.

File: CHANGELOG.md (hunk 7 above)
Comment (mglazer) [reply CHANGELOG.md]: Oh that's fantastic.

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 8 above)
Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Wow...I've never _not_ used slf4j.

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 4 above)
Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: I must have missed that. My bad

**Comment by casz** [comment]
The current discussion in #790 points to the need for doing version dancing :cry:

File: CHANGELOG.md (hunk 7 above)
Comment (casz) [reply CHANGELOG.md]: Ya, you can definitely remove this :smile:

**Comment by mglazer** [comment]
Ya, I'm happy to do the original thing I was doing to just support multiple versions. It's not crazy hard to add that back in.

Would that be better?

In any case, I think we still need to compile against the newer version right? Otherwise I'll have to do something really nasty and call by reflection.

**Comment by casz** [comment]
#808 should cover your build needs :smile:

**Comment by casz** [comment]
Feel free to rebase on master :sweat_smile:
Will be good to finally land this!

**Comment by casz** [comment]
ya rebase is your friend :smile: please revert the merge and do an actual rebase

**Comment by mglazer** [comment]
Ya...I know the difference. I primarily use gerrit, so the GH workflow is always...challenging.

**Comment by casz** [comment]
Give me a sec then I will fix the branch.

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java (hunk 1 above)
Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Resolved that this is needed still.

**Comment by mglazer** [comment]
I think I broke Jenkins?

**Comment by casz** [comment]
Nah, Jenkins been acting up most of the day.

**Comment by casz** [comment]
```
[ERROR] /home/travis/build/jenkinsci/configuration-as-code-plugin/plugin/src/test/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfiguratorTest.java:[52,9] cannot find symbol
[ERROR]   symbol:   variable Assume
[ERROR]   location: class io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfiguratorTest
```

**Comment by mglazer** [comment]
Got it sorted out!

File: plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java [hunk 9]
```diff
@@ -3,43 +3,78 @@
...
+        return target.getAllUsers().stream()
+                .map(u -> new UserWithPassword(u.getId(), null)) // password isn't actually stored, only hashed
+                .collect(Collectors.toList());
+    }
+
+    private static void setter(HudsonPrivateSecurityRealm target, Collection<UserWithPassword> value) throws IOException {
+        for (UserWithPassword user : value) {
+            if (user.password.startsWith(HASHED_PASSWORD_PREFIX) && jenkinsSupportsHashedPasswords()) {
+                try {
+                    target.createAccountWithHashedPassword(user.id, user.password);
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: we need to be able to compile with 2.60.3, yet signature is not there according to current target :sweat_smile:

Comment (mglazer) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Ya...in my original Jenkins PR I had made it so that the same method signature was used, it just detected the jbcrypt header and did magic. That was denied.

I guess I can use reflection here, which feels weird unless you know of a better way.

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java]: Reflection is the way to go

**Comment by mglazer** [comment]
Thank you!
