### ISSUE TITLE
CASC_JENKINS_CONFIG environment variable is not used anymore

### ISSUE THREAD

**Issue by batmat** [jenkinsci/configuration-as-code-plugin#203]
Seems like a recent commit broke the usage of the `CASC_JENKINS_CONFIG` environment variable to point to the CasC configuration file.

I found it out by updating to latest master of CasC in [evergreen](https://github.com/jenkins-infra/evergreen). It will be blocking us as long as we use latest tip of `master`.

I bisected the issue:

```
$ git bisect log
git bisect start 
# good: [987b55ffdf7e7468ac9b739e5d7bee6129cfa7fc] [maven-release-plugin] prepare release configuration-as-code-0.4-a
lpha 
git bisect good 987b55ffdf7e7468ac9b739e5d7bee6129cfa7fc 
# bad: [882d85351b045a33de7b91cf9cc5137d940a3626] Fix compilation error 
git bisect bad 882d85351b045a33de7b91cf9cc5137d940a3626 
# good: [8921814751e0465ba31b853b9adec18bb557f0ff] [maven-release-plugin] prepare release configuration-as-code-0.5-a
lpha 
git bisect good 8921814751e0465ba31b853b9adec18bb557f0ff 
# good: [4995ef13dc106f77bb121bcbaf25bd32157f68e3] integrations are not root elements 
git bisect good 4995ef13dc106f77bb121bcbaf25bd32157f68e3 
# skip: [bdf0f0f47fea6d7641fc9741113ac4293409fee7] merge yaml trees before applying configuration #184 
git bisect skip bdf0f0f47fea6d7641fc9741113ac4293409fee7 
# skip: [18f91bdca9f96c72300f57e459c183796725251e] use the same merge sample as reported in issue 
git bisect skip 18f91bdca9f96c72300f57e459c183796725251e 
# good: [2b45fd6392aba3f80eb805b437073064bc9cb1b7] improve attribute type safety and get/set while writing custom con
figurators 
git bisect good 2b45fd6392aba3f80eb805b437073064bc9cb1b7 
# only skipped commits left to test 
# possible first bad commit: [882d85351b045a33de7b91cf9cc5137d940a3626] Fix compilation error 
# possible first bad commit: [18f91bdca9f96c72300f57e459c183796725251e] use the same merge sample as reported in issu
e 
# possible first bad commit: [bdf0f0f47fea6d7641fc9741113ac4293409fee7] merge yaml trees before applying configuratio
n #184
```

cc @ndeloof  I think.

----
(This issue duplicates https://issues.jenkins-ci.org/browse/JENKINS-51283
Complying to your usage, though I think that using GH issues is not the common way in the Jenkinsci organization, and makes linking issues between different components more complex :-(.)
